FROM r-base:latest 
RUN R -e "install.packages(c('ggplot2', 'dplyr'), repos='http://cran.rstudio.com/')"
WORKDIR /Q5
COPY Q5/species_analysis.R /Q5/species_analysis.R
COPY Q5/species_data.csv /Q5/species_data.csv

CMD ["Rscript", "/Q5/species_analysis.R"]
